spring:

  datasource:
    url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:6543/postgres?user=postgres.njrreimpmqnuvkdndcnq&password=ibtihal2003A
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  docker:
    compose:
      file: src/main/docker/docker-compose.yml
      enabled: false

server:
  port: 8980

logging:
  level:
    root: INFO
    org.springframework: DEBUG
