spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trackpro
    username: ${DB_USERNAME:trackpro}
    password: ${DB_PASSWORD:trackpro}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      max-lifetime: 1800000
      auto-commit: true
      connection-timeout: 30000
  jpa:
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  docker:
    compose:
      file: src/main/docker/docker-compose.yml
      enabled: true

server:
  port: 8980

logging:
  level:
    root: INFO
    org.springframework: DEBUG
